jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Change directory to where your Maven project is located
      - name: Change to project directory
        run: cd foodmotion-food-products-service  # Update this to the correct directory if needed

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)

      - name: Build Image, Push to Registry, Deploy to Cloud Run
        run: |
          export IMAGE_NAME=europe-west1-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.APP_NAME}}/${{env.SER_NAME}}:$GITHUB_SHA
          echo "${KEY_FILE}" > client-secret.json
          gcloud auth activate-service-account ${{env.PROJECT_ID}}@appspot.gserviceaccount.com --key-file ${{env.PROJECT_ID}}-3f48ad93aa23.json
          gcloud config set project ${{env.PROJECT_ID}}
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          export DOCKER_BUILDKIT=0
          mvn test  # This command will now be executed within the correct directory
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          gcloud run deploy ${{env.SER_NAME}} --image $IMAGE_NAME --port ${{env.SER_PORT}} --region ${{env.REGION}} --cpu=2 --memory=8Gi --timeout=3000 --allow-unauthenticated || true
