# name: JaCoCo Agent - Maven Test

# on:
#   workflow_dispatch:
#   pull_request:
#   push:
#     branches:
#       - main
#       - 'releases/*'

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3
#       with:
#         ref: ${{ github.event.pull_request.head.sha }}
#         fetch-depth: 0

#     - name: Set up JDK 17
#       uses: actions/setup-java@v2
#       with:
#         java-version: '17'
#         distribution: 'adopt'
#         cache: 'maven'

#     - name: Qodana Scan
#       uses: JetBrains/qodana-action@main
#       env:
#         QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
#       with:
#         args: --baseline,qodana.sarif.json
 


name: JaCoCo Agent - Maven Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Validate Maven Wrapper
      run: mvn --version
      working-directory: food-products-service

    - name: Run Tests
      run: mvn test
      working-directory: food-products-service
      
    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: maven-coverage-data-jacoco
        path: food-products-service/.qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      with:
        args: "-i,food-products-service,--linter,jetbrains/qodana-jvm:latest"
        pr-mode: false